### PR TITLE
Full navigation extras support

### PR DESCRIPTION
**Pull request by Alex-Vaky**
for issue #74 with a more encompassing addition of supported navigation extras

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
@Alex-Vaky Would you mind writing a few unit tests to confirm the changes are being applied to the anchor correctly?
See: https://github.com/blackbaud/skyux-flyout/blob/master/src/app/public/modules/flyout/flyout.component.spec.ts#L794-L812

**Comment by Alex-Vaky** [comment]
@Blackbaud-SteveBrush can do.  Wanted to make sure this was an okay thing to do before putting in more effort 😛

**Comment by Alex-Vaky** [comment]
Do we prefer doing the more fully support work or just the work my team needs as shown in #75 ?

**Comment by Alex-Vaky** [comment]
gonna close this pr in favor of #75

**Pull request closed without merging**
