### PR TITLE
Fix flyout to not close when an element is removed immediately after being clicked

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null](https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null)

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-SteveBrush - this is unfortunately causing us to break other instances where we want the flyout to close when the element disappears.....

You can see this if you click the "show buttons" button outside of the flyout. This used to close the flyout (as it should) because the click happened outside of the flyout or any modals that were launched. However, after your change this is not closing the flyout.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null](https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null](https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null](https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null)

**Review by Blackbaud-TrevorBurch — CHANGES_REQUESTED** [review]
This change is breaking the last bug fix we did. If you reenable animations you'll see that if you try to trigger another flyout then things break and the flyout just closes with no animation and the other does not open.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null](https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null](https://developer.blackbaud.com/skyux-flyout?_sp.spa=pr-fix-click-element-null)

**Review by Blackbaud-TrevorBurch — APPROVED** [review]

**Comment by Blackbaud-KrisMahon** [comment]
It looks like a fix for this issue was merged into master 2 months ago, but I don't see a new package version for it yet.  Did someone just forget to create the new package version, or is there still more work to be done for this fix?

**Comment by Blackbaud-KrisMahon** [comment]
@Blackbaud-TrevorBurch @Blackbaud-SteveBrush Any thoughts on my comment above?

**Pull request merged**
